### ISSUE TITLE
Does not find variables and resources on PYTHONPATH / folders marked as "Sources"

### ISSUE THREAD

**Issue by a-w** [lte2000/intellibot#30]
When running, robotframework will find variables and resources files whose path is given relative to a component in PYTHONPATH.

This used to be supported by intellibot being able to find files in paths relative to any folder marked as "Sources" in the project structure, but does not work anymore with this version of the plugin (as of 0.10.143.397). Currently, it is necessary to provide a path relative to the referring file to find a variable or a resource file.

It should also work again for paths relative to any folder marked as "Sources", please.

**Comment by a-w** [comment]
`git bisect` says:
26152497501249da591a86b96f00d4fc182fd41b is the first bad commit (tagged dev_0.10.143.383)

**Comment by lte2000** [comment]
can you give an example?

**Comment by lte2000** [comment]
@a-w  please try https://github.com/lte2000/intellibot/raw/c697374f8b00a0f1fd0d25f70c7bb36c9fa78661/intellibot.jar

It resolve relative library/resource path according to current file first. If not found, it resolve the path relative to project "content root".

I ever try to resolve relative path in whole project in any directory, but it may result too many unwanted founds. So I restrict it to "relative to project content root".

**Comment by lte2000** [comment]
fixed in [v0.10.143.398](https://plugins.jetbrains.com/plugin/17424-intellibot-patched/versions/stable/134225)

**Comment by a-w** [comment]
> 
> 
> can you give an example?

Please find an example [here](https://github.com/a-w/lte2000-intellibot-issue-30)

The issue still persists with release `IntelliBot #patched 0.10.143.398`

>I ever try to resolve relative path in whole project in any directory, but it may result too many unwanted founds. So I restrict it to "relative to project content root".

I am not asking for "any directory". Im asking only that all directories which contribute to PYTHONPATH at runtime be used as bases for relative path evaluation in the plugin.

Rationale: by default, both content roots and source roots are used to populate PYTHONPATH at runtime, and that's what Robotframework uses to resolve relative paths. So, when RF is able to resolve a path, then the plugin should be able to resolve that same path too.

That used to work until dev_0.10.143.382 (and also in the original version from Millennial Media). The request is to restore the original search algorithm, as the behavior since dev_0.10.143.383 breaks many existing scripts (around 1k in my case).

If you think that limiting the search scope is necessary, you could provide options to select whether content and/or source roots should be used to resolve paths, but IMHO it is not a major performance concern to leave both on at all times. Usually, projects don't have that many source roots...

**Comment by lte2000** [comment]
@a-w please try this one,
search order of relative physical resource/library path: robot file, project source root, project content root
[intellibot.zip](https://github.com/lte2000/intellibot/files/7080761/intellibot.zip)

original version from Millennial Media it not suitable if you have multiple resource files having same name in different directory.
Current method improve this though in some situation it still match wrong file.

**Comment by tryb93** [comment]
I have the same problem.

**Comment by lte2000** [comment]
> 
> 
> I have the same problem.

@tryb93  do you still have the problem with https://github.com/lte2000/intellibot/files/7080761/intellibot.zip

**Comment by lte2000** [comment]
search order of relative physical resource/library path: 
- relative to current robot file, then project source root, then project content root

Implemented in version 0.11.191.8026
